Tunnelblick/Tunnelblick

third_party/Makefile-common, third_party/sources/patches/sparkle/add-default-includes-and-libs.diff
I originally wanted to add support for openvpn git version, but I ran across this issue building tunnelblick on OSX 10.11 (I see now that openvpn git version has been added :+1: )
This fixes #277 
The changes work like this
- Openvpn is built before sparkle, this is so that openssl can be built and statically linked in sparkle.
- ~~Headers from the openssl build are symlinked to the sparkle source directory~~
- ~~The headers are then updated to reflect this in the SUDSAVerifier.m file~~
- A patch is used to adjust the sparkle xcode project to include the built openssl headers and libs, this is then dynamically adjusted depending on your machine. This patch also links sparkle against libcrypto and libz.
~~There were some whitespace issues (because of using tabs) and this was problematic …
=> Add support for xcode 7.1+ (osx 10.11)

README.md
Previously it was the account URL
=> Fix repository URL

tunnelblick/VPNConnection.m
Sometimes the server sends 'Auth-Token' messages in the form:
'>PASSWORD:Auth-Token:xxxxxxxxxxxxxxxxxx' (Especially when
dealing with Challenge/Response mechanisms).
The current implementation mistakes these messages with a more
classical '>PASSWORD:Need 'Auth' username/password' message,
thus sends again username and password.
This is detected by the servers, which warns us that those
credentials were unexpected at that time.
While there is no harm sending unexpected credentials, I feel
it's more clean to handle (and ignore) those messages.
[Implementation is in OpenVPN](https://github.com/OpenVPN/openvpn/blob/master/src/openvpn/manage.c#L2716-L2720)
=> Ignore 'Auth-Token' messages from server.

tunnelblick/BuildAppsAndDmgs.sh
On a case-sensitive filesystem, setfile is not found - the proper
name being SetFile.
=> Changed setfile to SetFile (case-sensitive filesystem)

third_party/makefiles/Makefile-allssl
The design iterates over any file found in the sources directory
with a filespec regex of `.*/(libre|open){1}ssl-.*tar.gz$` and extracts and
builds it.
If you wish to exclude or include versions of SSL simply save them
into the sources directory and dependent versions of pkcs11-helper
and openvpn will iterate over the extracted versions building statically
against these.
Patches are located in third_party/sources/patches/ssl/ again prefixed
with the flavour of SSL.
=> This Makefile replaces Makefile-openssl.

third_party/makefiles/Makefile-allssl
On a case-sensitive filesystem, Configure is not found for libressl -
the proper filename being configure. (Configure is for openssl)
=> Case-sensitive filesystem : Change Configure to configure

tunnelblick/ConfigurationConverter.m, tunnelblick/sharedRoutines.m
Adds the new tls-crypt option available in OpenVPN 2.4
I don't have a Mac myself, so can't test it, sorry.
=> Add tls-crypt option

Building Tunnelblick from Source Code.markdown
Instead of directing people to change global Xcode settings which will affect their existing projects, it may be better to use the project-specific setting which works just as well.
=> Build doc: Changed legacy build direction to use project-specific setting.

tunnelblick/InfoView.h, tunnelblick/InfoView.m
Last change - sorry for the influx.
Manual scrolling wasn't stopped before completely, but it fought with the auto-scroll and was very jittery. Now it temporarily pauses the auto-scroll for at least one second.
=> Allow manual scrolling of credits

third_party/makefiles/Makefile-pkcs11-helper
The linking error comes when linking pkcs11-helper to OpenVPN (although it shouldn't really be happening since it's built statically).
pkcs11-helper will always prefer OpenSSL, which we are always using anyway (LibreSSL is compatible with OpenSSL), but it would still always try to link with GnuTLS, NNS and mbed TLS if they were found. Therefore we can safely disable using them, and disabling them fixes issues caused by them being linked.
=> Fixed linking error when GnuTLS, NSS or mbed TLS is found

third_party/README.txt
pkcs11-helper moved to github: https://github.com/OpenSC/pkcs11-helper
=> documentation link fix

tunnelblick/client.up.tunnelblick.sh
Fixes #402 
We should not assume DHCP just because of a lack of "route_vpn_gateway" env var, this is an open issue on openvpn:  https://community.openvpn.net/openvpn/ticket/668
It seems a safe bet to not use DHCP if there is already an IP address configured (i.e. by openvpn).
Please see further discussion on the issue.  Thanks!
=> Check for lack of IP addr before assuming DHCP

tunnelblick/FreePublicDnsServersList.txt
Added free and public dns in China. Here is a list of their websites (in Chinese):
114dns: http://www.114dns.com/about.html
alidns: http://www.alidns.com/
dnspod: https://www.dnspod.cn/products/public.dns
baiduDNS: https://dudns.baidu.com/intro/publicdns/
This list is not covered by http://pcsupport.about.com/od/tipstricks/a/free-public-dns-servers.htm, but most China users will use these public DNS in pushed network configurations. So it is confused to warn user while they do configure to use `114.114.114.114`.
> DNS servers '114.114.114.114' will be used for DNS queries when the VPN is active
> NOTE: The DNS servers do not include any free public DNS servers known to Tunnelblick. This may cause DNS queries to fail or be intercepted or falsified even if they are directed through the VPN. …
=> public-dns-list: add free and public dns in China

tunnelblick/client.up.tunnelblick.sh
It looks like there is an error in the regex. Currently it references the ".app" directory inside "/Applications/Tunnelblick". Changing "/" to "\\" should fix that.
=> Fix typo in regex in client.up.tunnelblick.sh

tunnelblick/Preferences.xib
* alignment of pref info view
* align contents left hand
* align title and description
* remove border
* use font mini for copyright typo
| before | after |
|---|---|
| ![Screen Shot 2019-05-22 at 12 44 39 PM](https://user-images.githubusercontent.com/26371/58171101-7962cc00-7c95-11e9-88b7-6d78f47f27c7.png) | ![Screen Shot 2019-05-22 at 1 22 46 PM](https://user-images.githubusercontent.com/26371/58171118-8384ca80-7c95-11e9-936b-f27d7a3ca187.png) |
🔗 #528
=> refine Info Preference view - alignment

tunnelblick/Preferences.xib
* fix Warnings label alignment
| before  | after |
|---|---|
| <img width="1032" alt="Screenshot 2019-06-03 at 11 11 57" src="https://user-images.githubusercontent.com/26371/58791530-ab0f5780-85f2-11e9-9259-92cea10e37b2.png">  | ![Screen Shot 2019-06-03 at 11 18 54 AM](https://user-images.githubusercontent.com/26371/58791553-b2366580-85f2-11e9-920c-cd9ac40a4bd9.png) |
🔗 #528
=> fix Warnings label alignment

tunnelblick/Preferences.xib
* use thin dividers for split view
* fix white pane splitter divider
* Apple HIG
* https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/split-views/
* > **Prefer the thin divider style.** Users are accustomed to the appearance of the thin divider. Consider the thick or pane splitter style when you need to indicate a stronger visual distinction between panes. For example, when each side of a split view contains a table, a wider divider can help people differentiate between the two tables.
| before | after |
|---|---|
| <img width="1033" alt="Screenshot_2019-06-03_at_14_57_16" src="https://user-images.githubusercontent.com/26371/58803739-77dbc100-8610-11e9-842a-b12ee0036484.png"> | ![Screen Shot 2019-06-03 at 2 57 40 …
=> use thin dividers for split view

tunnelblick/Preferences.xib
* align Preference Appearance consistently at `307x`
* consistent align content with `Preferences` & `Utilities` tab
| before | after |
|---|---|
| <img width="872" alt="Screenshot 2019-06-04 at 16 27 24" src="https://user-images.githubusercontent.com/26371/58888998-84334d00-86e8-11e9-8b78-8626f5b00cc7.png"> | ![Screen Shot 2019-06-04 at 4 43 26 PM](https://user-images.githubusercontent.com/26371/58889055-9d3bfe00-86e8-11e9-826e-58cba5774e4c.png) |
:link: #528
=> align Preference Appearance consistently

tunnelblick/defines.h
See https://community.openvpn.net/openvpn/wiki/DeprecatedOptions?__cf_chl_jschl_tk__=4689b08f0018d0c45915c209d40516ebf85d0f0a-1595849723-0-AdB4zIveQk-R8u6A8qxjqJSXR-q6cSsHinXjmSvbt6LfAsOKoVoGYP_wIVNz-s3K5JL8OuoMsYD59XuJr0OiUu8d1RbkpNb04Ot0rSP2yZ68E3PHbY3nPLOPmqV1ztVCrypc85Qtzk1C4enIAyFafgJ0dmYv_mjzngFYKccpjSbZl7gNoa_uBzOSEHk70gjer_TR-DTK3z9o0yWQv7xNYqOUYHQJvp0yq0SVhXhEMs6qC-ktzChqKeYPzvv_m2OBAualIyKbWkkA3m9N3cQNBnO6OCCdSUrDCLAHWcru33BtXAFkqDVij179mvETxnv2UQ#Option:--secret .
The --genkey case isn't very likely to be done in a configuation file and fed into Tunnelblick.
'secret' is also used in Static Key configurations, where it specifies the static key. This use is not deprecated.
See https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/ (search for "Enable Static Key …
=> --secret is only being removed in conjunction with --genkey

tunnelblick/AuthAgent.m, tunnelblick/LoginWindow-RTL.xib, tunnelblick/LoginWindow.xib, tunnelblick/LoginWindowController.h, tunnelblick/LoginWindowController.m
- Added a checkbox, input fields and a switch for visibility to the login window
- The input fields are for entering security tokens (e.g. YubiKey) without changing the password.
- This allows the use of security tokens together with passwords from the keychain.
- The password for openvpn is simply created by appending the security token to the password.
=> Support for security tokens added

third_party/makefiles/Makefile-openvpn, third_party/sources/openvpn/openvpn-2.4.11/patches/07-apple-iouserethernet.diff, third_party/sources/openvpn/openvpn-2.5.5/patches/11-apple-iouserethernet.diff, tunnelblick/MenuController.m, tunnelblick/VPNConnection.m
This patch uses IOUserEthernet to support TAP tunnels on macOS. 
This also changes the default behavior for tap kext to not be to always try to load it.
It fetches the missing header from apple directly since the header is listed as APSL to avoid conflicts with GPL.
I'm happy to make or accept changes or work with you to clean up anything necessary.  I will be submitting the patch upstream but I suspect this might be a good place to get it ironed out more first, and you're welcome to do the upstream submission as well.
The patch is not yet applied to the oldest version of openvpn bundled.  It works with the two newer versions.
=> Support native macOS IOUserEthernet devices for TAP

tunnelblick/tunnelblick-helper.m
Tunnelblick supports crtext for quite some time. It works fine. We should announce that, too.
Then servers could select the method they support.
Now: IV_SSO=webauth
Then: IV_SSO=webauth,crtext
We are using crtext with Tunnelblick in production. But currently we need a special solution for Tunnelblick, because it doesn't announce its support for crtext. We don't support webauth on server side.
Extends #767
=> Announce crtext support, too

tunnelblick/VPNConnection.m
See Tunnelblick#676 for protocol details. This change is a simple implementation and has some TODO left as I'm not an Objective-C developer at all.
Tested locally.
=> Adds support for client-pending-auth using INFOMSG:CR_TEXT request
